### ISSUE TITLE
Unable to build collections

### ISSUE THREAD

**Issue by doncaballero89** [Kometa-Team/Kometa#1749]
### Version Number

1.19.0

### What branch are you on?

master

### Describe the Bug

Today I was expecting a Christmas movies collection to be added to Plex, but it hasnt worked. Previous seasonal collections have worked in the past. 

The logs seem to show an issue with Server.py

Any ideas whats causing this? or should I just reinstall PMM? 

[2023-12-01 10:48:54,755] [builder.py:198]            [INFO]     |====================================================================================================|
[2023-12-01 10:48:54,756] [builder.py:198]            [INFO]     |                               Christmas Movies Collection in Movies                                |
[2023-12-01 10:48:54,757] [builder.py:198]            [INFO]     |====================================================================================================|
[2023-12-01 10:48:54,757] [builder.py:199]            [INFO]     |                                                                                                    |
[2023-12-01 10:48:54,761] [builder.py:210]            [INFO]     |================================ Building Definition From Templates ================================|
[2023-12-01 10:48:54,762] [builder.py:211]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:54,762] [builder.py:221]            [DEBUG]    | Templates Called: holiday, shared, arr                                                             |
[2023-12-01 10:48:54,763] [builder.py:222]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:54,774] [meta.py:355]               [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:54,774] [meta.py:356]               [DEBUG]    | Conditional: name_<<key>>                                                                          |
[2023-12-01 10:48:54,775] [meta.py:355]               [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:54,775] [meta.py:356]               [DEBUG]    | Conditional: summary_<<key>>                                                                       |
[2023-12-01 10:48:54,777] [meta.py:554]               [INFO]     |                                                                                                    |
[2023-12-01 10:48:54,777] [meta.py:555]               [WARNING]  | Template Warning: template attribute: translation_key from shared skipped                          |
[2023-12-01 10:48:54,778] [meta.py:554]               [INFO]     |                                                                                                    |
[2023-12-01 10:48:54,778] [meta.py:555]               [WARNING]  | Template Warning: template attribute: key_name from shared skipped                                 |
[2023-12-01 10:48:54,792] [meta.py:562]               [DEBUG]    |==================================== Final Template Attributes =====================================|
[2023-12-01 10:48:54,793] [meta.py:563]               [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:54,794] [meta.py:564]               [DEBUG]    | {'smart_label': {'sort_by': 'title.asc', 'all': {'label': '<<smart_label>>'}}, 'schedule': 'range(11/30-12/31)', 'delete_not_scheduled': True, 'sync_mode': 'sync', 'imdb_list': ['https://www.imdb.com/list/ls000096828/'], 'cache_builders': 1, 'translation_key': 'seasonal', 'key_name': 'Christmas', 'translation_prefix': '🎅 ', 'ignore_blank_results': True, 'visible_home': True, 'visible_shared': True, 'sort_title': '!00_<<title>>', 'url_poster': 'https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/seasonal/christmas.jpg'} |
[2023-12-01 10:48:54,794] [meta.py:565]               [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:54,795] [builder.py:238]            [INFO]     |============================== Validating Christmas Movies Attributes ==============================|
[2023-12-01 10:48:54,795] [builder.py:277]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:54,796] [builder.py:278]            [DEBUG]    | Validating Method: key_name                                                                        |
[2023-12-01 10:48:54,796] [builder.py:291]            [DEBUG]    | Value: Christmas                                                                                   |
[2023-12-01 10:48:54,797] [builder.py:302]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:54,797] [builder.py:303]            [DEBUG]    | Validating Method: translation_key                                                                 |
[2023-12-01 10:48:54,797] [builder.py:306]            [DEBUG]    | Value: seasonal                                                                                    |
[2023-12-01 10:48:54,798] [builder.py:319]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:54,798] [builder.py:320]            [DEBUG]    | Validating Method: translation_prefix                                                              |
[2023-12-01 10:48:54,799] [builder.py:321]            [DEBUG]    | Value: 🎅                                                                                           |
[2023-12-01 10:48:54,799] [builder.py:386]            [INFO]     | 🎅 Christmas Movies                                                                                 |
[2023-12-01 10:48:54,803] [plex.py:940]               [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:54,804] [plex.py:943]               [DEBUG]    | Looking for: 🎅 Christmas Movies                                                                    |
[2023-12-01 10:48:54,804] [builder.py:626]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:54,805] [builder.py:627]            [DEBUG]    | Validating Method: ignore_blank_results                                                            |
[2023-12-01 10:48:54,805] [builder.py:628]            [DEBUG]    | Value: True                                                                                        |
[2023-12-01 10:48:54,805] [builder.py:636]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:54,806] [builder.py:637]            [DEBUG]    | Validating Method: smart_label                                                                     |
[2023-12-01 10:48:54,806] [builder.py:642]            [DEBUG]    | Value: {'sort_by': 'title.asc', 'all': {'label': '<<smart_label>>'}}                               |
[2023-12-01 10:48:54,809] [builder.py:663]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:54,810] [builder.py:664]            [DEBUG]    | Validating Method: delete_not_scheduled                                                            |
[2023-12-01 10:48:54,810] [builder.py:665]            [DEBUG]    | Value: True                                                                                        |
[2023-12-01 10:48:54,810] [builder.py:682]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:54,811] [builder.py:683]            [DEBUG]    | Validating Method: schedule                                                                        |
[2023-12-01 10:48:54,811] [builder.py:687]            [DEBUG]    | Value: range(11/30-12/31)                                                                          |
[2023-12-01 10:48:54,812] [builder.py:742]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:54,812] [builder.py:743]            [DEBUG]    | Validating Method: sync_mode                                                                       |
[2023-12-01 10:48:54,813] [builder.py:747]            [DEBUG]    | Value: sync                                                                                        |
[2023-12-01 10:48:54,813] [builder.py:886]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:54,813] [builder.py:890]            [DEBUG]    | Validating Method: imdb_list                                                                       |
[2023-12-01 10:48:54,814] [builder.py:891]            [DEBUG]    | Value: ['https://www.imdb.com/list/ls000096828/']                                                  |
[2023-12-01 10:48:58,656] [builder.py:886]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:58,656] [builder.py:890]            [DEBUG]    | Validating Method: cache_builders                                                                  |
[2023-12-01 10:48:58,657] [builder.py:891]            [DEBUG]    | Value: 1                                                                                           |
[2023-12-01 10:48:58,657] [builder.py:886]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:58,658] [builder.py:890]            [DEBUG]    | Validating Method: visible_home                                                                    |
[2023-12-01 10:48:58,659] [builder.py:891]            [DEBUG]    | Value: True                                                                                        |
[2023-12-01 10:48:58,659] [builder.py:886]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:58,660] [builder.py:890]            [DEBUG]    | Validating Method: visible_shared                                                                  |
[2023-12-01 10:48:58,660] [builder.py:891]            [DEBUG]    | Value: True                                                                                        |
[2023-12-01 10:48:58,661] [builder.py:886]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:58,661] [builder.py:890]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2023-12-01 10:48:58,661] [builder.py:891]            [DEBUG]    | Value: !00_<<title>>                                                                               |
[2023-12-01 10:48:58,662] [builder.py:886]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:58,663] [builder.py:890]            [DEBUG]    | Validating Method: url_poster                                                                      |
[2023-12-01 10:48:58,663] [builder.py:891]            [DEBUG]    | Value: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/seasonal/christmas.jpg |
[2023-12-01 10:48:58,981] [builder.py:992]            [DEBUG]    |                                                                                                    |
[2023-12-01 10:48:58,981] [builder.py:993]            [DEBUG]    | Validating Method: append_label                                                                    |
[2023-12-01 10:48:58,982] [builder.py:994]            [DEBUG]    | Value: Seasonal                                                                                    |
[2023-12-01 10:48:58,988] [plex_meta_manager.py:833]  [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "C:\Users\Media Server\Plex-Meta-Manager\plex_meta_manager.py", line 691, in run_collection |
                                                                 |     builder = CollectionBuilder(config, metadata, mapping_name, collection_attrs, library=library, extra=output_str) |
                                                                 |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "C:\Users\Media Server\Plex-Meta-Manager\modules\builder.py", line 1054, in __init__        |
                                                                 |     self.beginning_count = len(self.library.get_filter_items(check_url))                           |
                                                                 |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                            |
                                                                 |   File "C:\Users\Media Server\Plex-Meta-Manager\modules\plex.py", line 1087, in get_filter_items   |
                                                                 |     return self.Plex._search(key, None, 0, plexapi.X_PLEX_CONTAINER_SIZE)                          |
                                                                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                          |
                                                                 |   File "C:\Users\Media Server\Plex-Meta-Manager\pmm-venv\Lib\site-packages\plexapi\library.py", line 1532, in _search |
                                                                 |     subresults = self.fetchItems(key, container_start=container_start,                             |
                                                                 |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                             |
                                                                 |   File "C:\Users\Media Server\Plex-Meta-Manager\pmm-venv\Lib\site-packages\plexapi\library.py", line 442, in fetchItems |
                                                                 |     data = self._server.query(ekey, params=url_kw)                                                 |
                                                                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                 |
                                                                 |   File "C:\Users\Media Server\Plex-Meta-Manager\pmm-venv\Lib\site-packages\plexapi\server.py", line 753, in query |
                                                                 |     raise NotFound(message)                                                                        |
                                                                 | plexapi.exceptions.NotFound: (404) not_found; (redacted)/library/sections/9/allNone?X-Plex-Container-Start=0&X-Plex-Container-Size=100 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html> |
                                                                 |                                                                                                    |
[2023-12-01 10:48:58,996] [plex_meta_manager.py:834]  [ERROR]    | Unknown Error: (404) not_found; (redacted)/library/sections/9/allNone?X-Plex-Container-Start=0&X-Plex-Container-Size=100 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html> |
[2023-12-01 10:48:58,996] [plex_meta_manager.py:839]  [INFO]     |                                                                                                    |
[2023-12-01 10:48:58,997] [plex_meta_manager.py:840]  [INFO]     |====================================================================================================|
[2023-12-01 10:48:58,997] [plex_meta_manager.py:840]  [INFO]     |                                Finished Christmas Movies Collection                                |
[2023-12-01 10:48:58,998] [plex_meta_manager.py:840]  [INFO]     |                                    Collection Run Time: 0:00:04                                    |
[2023-12-01 10:48:58,998] [plex_meta_manager.py:840]  [INFO]     |====================================================================================================|

**Comment by chazlarson** [comment]
That issue is fixed in the develop branch of PMM, or you can downgrade to Plex 1.32.6.

**Comment by christiandwood** [comment]
I switched over to the develop branch because I was getting the same error as above, but now when I run it I get a different error (500):
Attached
[christmasmovies.txt](https://github.com/meisnate12/Plex-Meta-Manager/files/13528121/christmasmovies.txt)

**Comment by chazlarson** [comment]
That's a regression that Plex introduced in Plex 1.32.7.

copy-paste announcement from Discord:

### What does the error look like?
```
(500) internal_server_error; (redacted)/library/sections/1/all?includeGuids=1&label=LABEL_TEXT_APPEARS_HERE&X-Plex-Container-Start=0&X-Plex-Container-Size=100 <html><head><title>Internal Server Error</title>
```

### Why does it happen?
This is a Plex-side regression in 1.32.7.

In Plex 1.32.6 or below and Plex 1.32.8 or above, searching via the API for a non-existent tag returns an empty list.

In 1.32.7, it fails with this error.

### What can I do about it?

1. Downgrade to Plex 1.32.6
2. Upgrade to Plex 1.32.8
3. Apply the relevant sharing label [it will be in your log where "LABEL_TEXT_APPEARS_HERE" is in the example above] to any one item in the relevant library.  The label might contains an url-encoded emoji like `%F0%9F%A6%83+Thanksgiving+Movies`; in that case you can get the actual label to copy-paste from the relevant default page [probably seasonal]

**Comment by christiandwood** [comment]
Thanks for the info, I will downgrade to 1.32.6 since 1.32.8 is still in beta.

**Comment by ppetro08** [comment]
I just updated to Plex 1.32.8.7639 and I'm still getting the same issue. Looks like I may need to change over to develop for PMM as well.

**Comment by chazlarson** [comment]
> getting the same issue

Which issue?  The 404 or the 500?

**Comment by ppetro08** [comment]
Sorry my eyes glossed over the fact that your comment was about the 500 error. Changing over to the PMM develop branch did fix the 404 issue.
